server:
  port: 8000
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.dodaily.cn:3306/daily?useUnicode=true&characterEncoding=utf-8
    username: daily
    password: daily

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
